# Generated by Django 5.0.4 on 2024-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="heading",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
