# Generated by Django 5.0.4 on 2024-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_customuser_userprofile_delete_library"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("phone_no", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
        ),
    ]
