# Generated by Django 5.0.6 on 2024-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_customuser_address_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("cover_image", models.ImageField(upload_to="book_covers/")),
            ],
        ),
    ]
