# Generated by Django 5.0.6 on 2024-05-29 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
