# Generated by Django 5.0.7 on 2024-08-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='image_url',
        ),
    ]
