# Generated by Django 5.0.6 on 2024-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("review", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
    ]
