# Generated by Django 5.0.6 on 2024-05-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_bookreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreview",
            name="rating",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
